# Generated by Django 4.1 on 2022-09-15 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cosmetic_site", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=200)),
                ("email", models.TextField()),
                ("procedure", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=200)),
                ("initial_fund", models.CharField(max_length=200)),
                ("balance_fund", models.CharField(max_length=200)),
                ("public", models.BooleanField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
