# Generated by Django 4.1 on 2022-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_site', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=200)),
                ('expiry_date', models.CharField(max_length=200)),
                ('cvv', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
